### ISSUE TITLE
openfhe-python on windows

### ISSUE THREAD

**Issue by zubeydeulukok** [openfheorg/openfhe-python#57] opened 2023-08-17 08:11 UTC
@reneroliveira There is only Linux install in the repo. Can’t we use openfhe-python wrapper on windows?What should I do to use openfhe-python as windows user?

**Comment by reneroliveira** [comment] 2023-08-17 11:35
Sure, you can use the wrapper on Windows too. The recommend way is following the [OpenFHE C++  installation instructions for Windows](https://openfhe-development.readthedocs.io/en/latest/sphinx_rsts/intro/installation/windows.html), and then replicate the commands for the python wrapper in the MSYS2 terminal. We are testing and validating this process and soon we'll add detailed description in the readme.

Any problem or comment, feel free to reach out!

**Comment by zubeydeulukok** [comment] 2023-08-17 12:21
@reneroliveira Actually, I installed openfhe and openfhe-python libraries in colab, but I cannot import. What would be the reason? I'm adding the Colab link in case you want to take a look:
https://drive.google.com/file/d/1Ho58YXPXKwSMiJITVHn4WpiraUYb0kQR/view?usp=sharing

**Comment by reneroliveira** [comment] 2023-08-17 12:26
I suspect the problem is the library installation path. I don't know how colab works, but if you have more than one python installations, you have to take care and make sure you're installing in the right path
Try running !which python (or maybe !which python3) in a colab cell to see the path.

When installing OpenFHE-python you can specify the python binary path in the cake step, this procedure is documented in Readme.

**Comment by zubeydeulukok** [comment] 2023-08-17 14:03
In colab, after installing "[openfhe-development](https://github.com/openfheorg/openfhe-development)" run  sudo ldconfig . Running sudo ldconfig refreshes the system's cache of dynamic linkers and their associated libraries, ensuring that any changes or new installations are recognized by the system. It's a crucial step after installing or updating libraries to make sure that programs can find and link to the appropriate shared libraries during runtime.

**Comment by IanQS** [comment] 2023-08-26 14:28
^ Sounds like this issue has been resolved. If so, please close it :) Thank you!

**Comment by yspolyakov** [comment] 2023-09-26 14:53
@zubeydeulukok can this issue be closed?

**Comment by IanQS** [comment] 2024-01-24 04:39
Stale issue and the topic changed to Colab. If it's still an issue please open a new issue with updated errors and information

**Closed** 2024-01-24 04:39 UTC
